export const TOP_FOUR = "TOP_FOUR"
export const TOP_FOUR_LOAD = "TOP_FOUR_LOAD"
export const TOP_TEN = "TOP_TEN"
export const TOP_TEN_LOAD = "TOP_TEN_Load"
export const GET_COINS = "GET_COINS"
export const GET_COIN = "GET_COIN"
export const COIN_LOAD = "COIN_LOAD"